%YAML 1.2
---
dataset_dir: ./data/48/
train_output_dir:  ./outputs/  # /<base_out_dir>/exp_name is recommended

experiment_num: 3

num_workers: 1

batch_size: 100

# optimizer
optimizer: AdamW  # 'SGD, Adam, AdamW'
opt_param: all  # 'all', 'net_coarse', 'net_fine'
max_lr: 0.0001
max_epoch: 10
weight_decay: 0

fine_tune: False
fine_tune_params:
  max_epoch: 30
  lr: !!float 1e-4
  momentum: 0.9

# log & display
disp_interval: 100